let str1 = new String("welcome to typescript to learn")
let str2="welcome to typescript to learn"
console.log(str1.valueOf())
console.log("string length:",str1.length)
console.log("charAt",str1.charAt(2))
console.log("charAt",str1.charCodeAt(2))
console.log("indexof",str1.indexOf("to",2))
console.log("lastindexof",str1.lastIndexOf("to"))
console.log("search",str1.search("to"))
console.log("replace",str1.replace("to","2"))
console.log("substr",str1.substr(2,5))
console.log("substring",str1.substring(2,5))
console.log("slice",str1.slice(2,5))
console.log("split",str1.split('',5))